# Generated by Django 5.0.6 on 2024-07-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
